name: vault_shield_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf:
  shelf_router:
  mongo_dart:
  dbcrypt:
  dart_jsonwebtoken:
  pointycastle:
  http: ^1.2.1
  conduit_password_hash:
  crypton:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
